### ISSUE TITLE
just to ipmiview internal path to run app?

### ISSUE THREAD

**Issue by Jerning** [TheCase/IPMIView.app#14]
i try to outside path run ipmiview app and tap to sensors

$ java -jar Applications/IPMIView.app/Contents/Resources/IPMIView/IPMIView20.jar
Exception in thread "Thread-24" java.lang.IndexOutOfBoundsException: Range [48, 48 + -16) out of bounds for length 128
	at java.base/jdk.internal.util.Preconditions.outOfBounds(Preconditions.java:64)
	at java.base/jdk.internal.util.Preconditions.outOfBoundsCheckFromIndexSize(Preconditions.java:82)
	at java.base/jdk.internal.util.Preconditions.checkFromIndexSize(Preconditions.java:343)
	at java.base/java.util.Objects.checkFromIndexSize(Objects.java:425)
	at java.base/java.io.ByteArrayOutputStream.write(ByteArrayOutputStream.java:129)
	at IPMIView20.Sensors20.GetSDRRecords(Sensors20.java:1528)
	at IPMIView20.Sensors20.GetSensors(Sensors20.java:515)
	at IPMIView20.IPMISession$16.run(IPMISession.java:1193)

**Comment by TheCase** [comment]
Sorry - that is problem between Java and IPMIView jar file.  It is not an issue with the wrapper.
